# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(220, 811)
        Form.setMaximumSize(QtCore.QSize(220, 811))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.doubleSpinBox_rotate = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rotate.setDecimals(1)
        self.doubleSpinBox_rotate.setMinimum(-360.0)
        self.doubleSpinBox_rotate.setMaximum(360.0)
        self.doubleSpinBox_rotate.setObjectName("doubleSpinBox_rotate")
        self.horizontalLayout.addWidget(self.doubleSpinBox_rotate)
        self.btn_rotate = QtWidgets.QPushButton(Form)
        self.btn_rotate.setObjectName("btn_rotate")
        self.horizontalLayout.addWidget(self.btn_rotate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.btn_updown = QtWidgets.QPushButton(Form)
        self.btn_updown.setObjectName("btn_updown")
        self.horizontalLayout_2.addWidget(self.btn_updown)
        self.btn_leftright = QtWidgets.QPushButton(Form)
        self.btn_leftright.setObjectName("btn_leftright")
        self.horizontalLayout_2.addWidget(self.btn_leftright)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.spinBox_w = QtWidgets.QSpinBox(Form)
        self.spinBox_w.setMinimum(1)
        self.spinBox_w.setMaximum(10000)
        self.spinBox_w.setObjectName("spinBox_w")
        self.gridLayout.addWidget(self.spinBox_w, 2, 1, 1, 1)
        self.spinBox_h = QtWidgets.QSpinBox(Form)
        self.spinBox_h.setMinimum(1)
        self.spinBox_h.setMaximum(10000)
        self.spinBox_h.setProperty("value", 18)
        self.spinBox_h.setObjectName("spinBox_h")
        self.gridLayout.addWidget(self.spinBox_h, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.doubleSpinBox_rate = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rate.setSingleStep(0.1)
        self.doubleSpinBox_rate.setProperty("value", 1.0)
        self.doubleSpinBox_rate.setObjectName("doubleSpinBox_rate")
        self.gridLayout.addWidget(self.doubleSpinBox_rate, 3, 1, 1, 1)
        self.btn_rate = QtWidgets.QPushButton(Form)
        self.btn_rate.setObjectName("btn_rate")
        self.gridLayout.addWidget(self.btn_rate, 3, 2, 1, 1)
        self.btn_hw = QtWidgets.QPushButton(Form)
        self.btn_hw.setObjectName("btn_hw")
        self.gridLayout.addWidget(self.btn_hw, 1, 2, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 6, 0, 1, 1)
        self.comboBox_prewitt = QtWidgets.QComboBox(Form)
        self.comboBox_prewitt.setObjectName("comboBox_prewitt")
        self.comboBox_prewitt.addItem("")
        self.comboBox_prewitt.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_prewitt, 4, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 4)
        self.btn_laplace = QtWidgets.QPushButton(Form)
        self.btn_laplace.setObjectName("btn_laplace")
        self.gridLayout_2.addWidget(self.btn_laplace, 6, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 2)
        self.btn_robert = QtWidgets.QPushButton(Form)
        self.btn_robert.setObjectName("btn_robert")
        self.gridLayout_2.addWidget(self.btn_robert, 3, 3, 1, 1)
        self.btn_sobel = QtWidgets.QPushButton(Form)
        self.btn_sobel.setObjectName("btn_sobel")
        self.gridLayout_2.addWidget(self.btn_sobel, 5, 3, 1, 1)
        self.comboBox_l = QtWidgets.QComboBox(Form)
        self.comboBox_l.setObjectName("comboBox_l")
        self.comboBox_l.addItem("")
        self.comboBox_l.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_l, 6, 2, 1, 1)
        self.comboBox_gauss_size = QtWidgets.QComboBox(Form)
        self.comboBox_gauss_size.setObjectName("comboBox_gauss_size")
        self.comboBox_gauss_size.addItem("")
        self.comboBox_gauss_size.addItem("")
        self.comboBox_gauss_size.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_gauss_size, 8, 2, 1, 1)
        self.comboBox_sobel = QtWidgets.QComboBox(Form)
        self.comboBox_sobel.setObjectName("comboBox_sobel")
        self.comboBox_sobel.addItem("")
        self.comboBox_sobel.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_sobel, 5, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 7, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 8, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 9, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 2)
        self.doubleSpinBox_gauss_sigma = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_gauss_sigma.setObjectName("doubleSpinBox_gauss_sigma")
        self.gridLayout_2.addWidget(self.doubleSpinBox_gauss_sigma, 7, 2, 1, 1)
        self.comboBox_avg = QtWidgets.QComboBox(Form)
        self.comboBox_avg.setObjectName("comboBox_avg")
        self.comboBox_avg.addItem("")
        self.comboBox_avg.addItem("")
        self.comboBox_avg.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_avg, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 7, 0, 2, 1)
        self.comboBox_mid = QtWidgets.QComboBox(Form)
        self.comboBox_mid.setObjectName("comboBox_mid")
        self.comboBox_mid.addItem("")
        self.comboBox_mid.addItem("")
        self.comboBox_mid.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_mid, 1, 2, 1, 1)
        self.btn_avg = QtWidgets.QPushButton(Form)
        self.btn_avg.setObjectName("btn_avg")
        self.gridLayout_2.addWidget(self.btn_avg, 2, 3, 1, 1)
        self.btn_mid = QtWidgets.QPushButton(Form)
        self.btn_mid.setObjectName("btn_mid")
        self.gridLayout_2.addWidget(self.btn_mid, 1, 3, 1, 1)
        self.comboBox_l48 = QtWidgets.QComboBox(Form)
        self.comboBox_l48.setObjectName("comboBox_l48")
        self.comboBox_l48.addItem("")
        self.comboBox_l48.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_l48, 6, 1, 1, 1)
        self.btn_prewitt = QtWidgets.QPushButton(Form)
        self.btn_prewitt.setObjectName("btn_prewitt")
        self.gridLayout_2.addWidget(self.btn_prewitt, 4, 3, 1, 1)
        self.comboBox_robert = QtWidgets.QComboBox(Form)
        self.comboBox_robert.setObjectName("comboBox_robert")
        self.comboBox_robert.addItem("")
        self.comboBox_robert.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_robert, 3, 1, 1, 2)
        self.btn_gauss = QtWidgets.QPushButton(Form)
        self.btn_gauss.setObjectName("btn_gauss")
        self.gridLayout_2.addWidget(self.btn_gauss, 7, 3, 2, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 10, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 9, 0, 2, 1)
        self.btn_canny = QtWidgets.QPushButton(Form)
        self.btn_canny.setObjectName("btn_canny")
        self.gridLayout_2.addWidget(self.btn_canny, 9, 3, 2, 1)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 10, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "工具箱🧰"))
        self.label_2.setText(_translate("Form", "旋转"))
        self.btn_rotate.setText(_translate("Form", "确认"))
        self.label_3.setText(_translate("Form", "翻转"))
        self.btn_updown.setText(_translate("Form", "上下"))
        self.btn_leftright.setText(_translate("Form", "左右"))
        self.label_4.setText(_translate("Form", "缩放"))
        self.label_6.setText(_translate("Form", "宽度"))
        self.label_5.setText(_translate("Form", "高度"))
        self.label_7.setText(_translate("Form", "倍数"))
        self.btn_rate.setText(_translate("Form", "确认"))
        self.btn_hw.setText(_translate("Form", "确认"))
        self.label_12.setText(_translate("Form", "Laplace"))
        self.comboBox_prewitt.setItemText(0, _translate("Form", "不叠加"))
        self.comboBox_prewitt.setItemText(1, _translate("Form", "叠加"))
        self.label_8.setText(_translate("Form", "平滑与增强"))
        self.btn_laplace.setText(_translate("Form", "确认"))
        self.label_17.setText(_translate("Form", "均值滤波"))
        self.btn_robert.setText(_translate("Form", "确认"))
        self.btn_sobel.setText(_translate("Form", "确认"))
        self.comboBox_l.setItemText(0, _translate("Form", "不叠加"))
        self.comboBox_l.setItemText(1, _translate("Form", "叠加"))
        self.comboBox_gauss_size.setItemText(0, _translate("Form", "3"))
        self.comboBox_gauss_size.setItemText(1, _translate("Form", "5"))
        self.comboBox_gauss_size.setItemText(2, _translate("Form", "7"))
        self.comboBox_sobel.setItemText(0, _translate("Form", "不叠加"))
        self.comboBox_sobel.setItemText(1, _translate("Form", "叠加"))
        self.label_11.setText(_translate("Form", "Sobel"))
        self.label_9.setText(_translate("Form", "Prewitt"))
        self.label_10.setText(_translate("Form", "Robert"))
        self.label_15.setText(_translate("Form", "sigma"))
        self.label_18.setText(_translate("Form", "size"))
        self.label_16.setText(_translate("Form", "中值滤波"))
        self.comboBox_avg.setItemText(0, _translate("Form", "3"))
        self.comboBox_avg.setItemText(1, _translate("Form", "5"))
        self.comboBox_avg.setItemText(2, _translate("Form", "7"))
        self.label_13.setText(_translate("Form", "Gauss"))
        self.comboBox_mid.setItemText(0, _translate("Form", "3"))
        self.comboBox_mid.setItemText(1, _translate("Form", "5"))
        self.comboBox_mid.setItemText(2, _translate("Form", "7"))
        self.btn_avg.setText(_translate("Form", "确认"))
        self.btn_mid.setText(_translate("Form", "确认"))
        self.comboBox_l48.setItemText(0, _translate("Form", "4领域"))
        self.comboBox_l48.setItemText(1, _translate("Form", "8领域"))
        self.btn_prewitt.setText(_translate("Form", "确认"))
        self.comboBox_robert.setItemText(0, _translate("Form", "不叠加"))
        self.comboBox_robert.setItemText(1, _translate("Form", "叠加"))
        self.btn_gauss.setText(_translate("Form", "确认"))
        self.label_14.setText(_translate("Form", "canny"))
        self.btn_canny.setText(_translate("Form", "确认"))
        self.label_19.setText(_translate("Form", "low"))
        self.label_20.setText(_translate("Form", "high"))
